---
# Variables listed here are applicable to "mysql" roles
django_dir: /src/djangorest/scrum 
settings: djangoapp.settings
admin_user: vagrant 
admin_email: admin@example.com
admin_pass: kk123 
app_path: /src/djangorest/scrum 








admin_email: dtorresrangel@gmail.com
admin_user: vagrant 
django_superuser_username: vagrant
gunicorn:
  mysql_superuser_home: /root
  user: root
  old_password: root
  new_password: password 
  hosts:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
  privileges: "*.*:ALL,GRANT"

